@startuml

title __OBSERVEREXAMPLE's Class Diagram__\n

  namespace com.yugandhar {
    namespace observerexample {
      class com.yugandhar.observerexample.ConcreteObserver {
          + observableList : List<Observer>
          + addObserver()
          + notify()
          + removeObserver()
      }
    }
  }
  

  namespace com.yugandhar {
    namespace observerexample {
      class com.yugandhar.observerexample.FooObservable {
          - fooObservableConcreteObserver : ConcreteObserver<FooObservable>
          - state : String
          + addObserver()
          + getState()
          + removeObserver()
          + setState()
      }
    }
  }
  

  namespace com.yugandhar {
    namespace observerexample {
      class com.yugandhar.observerexample.FooObserver {
          + update()
      }
    }
  }
  

  namespace com.yugandhar {
    namespace observerexample {
      class com.yugandhar.observerexample.ObserExampleMain {
          {static} + main()
      }
    }
  }
  

  namespace com.yugandhar {
    namespace observerexample {
      interface com.yugandhar.observerexample.Observable {
          {abstract} + addObserver()
          {abstract} + removeObserver()
      }
    }
  }
  

  namespace com.yugandhar {
    namespace observerexample {
      interface com.yugandhar.observerexample.Observer {
          {abstract} + update()
      }
    }
  }
  

  com.yugandhar.observerexample.ConcreteObserver .up.|> com.yugandhar.observerexample.Observable
  com.yugandhar.observerexample.FooObservable .up.|> com.yugandhar.observerexample.Observable
  com.yugandhar.observerexample.FooObserver .up.|> com.yugandhar.observerexample.Observer
  com.yugandhar.observerexample.FooObserver o-- com.yugandhar.observerexample.FooObservable : fooObservable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
